### ISSUE TITLE
Wrong names for classes

### ISSUE THREAD

**Issue by ghost** [sandboxnu/searchneu-old#102]
Some courses occasionally have the wrong name.

MATH 1252: Calc & Diff Eq -Biol 2 (HON)
vs
MATH 1252 - Calculus and Differential Equations for Biology 2
can be seen [here](https://searchneu.com/202030/math+1252).

<img width="1131" alt="Screen Shot 2019-11-28 at 3 59 56 PM" src="https://user-images.githubusercontent.com/22948432/69835665-2a739180-11f8-11ea-9ebd-a393f78cb67a.png">

Search seems to be scraping the **first** section in the schedule listing (usually the honors section), which can be found [here](https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202030&subj_in=MATH&crse_in=1252&schd_in=LEC) for the above.

It seems that rather than using the [Class Schedule Listing](https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202030&subj_in=MATH&crse_in=1252&schd_in=LEC) page, it should instead be using the [Detailed Course Information](https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202030&subj_code_in=MATH&crse_numb_in=1252) page.

This also occurs for CHEM 1214, and PHYS 1152. Seems to always be honors courses.

**Comment by NEUDitao** [comment]
It's the same thing as the fundies 2 description then @dajinchu , maybe we should do the extra parsing on all fields..

**Comment by ryanhugh** [comment]
Oh yeah it was the same on Banner v8 too. Each class had a title on the course catalog page, and then each section in the class had a title too. Most of the times the sections had the same title as the course catalog page, but not always. There was a bunch of times like this - where they had abbreviations instead. 

Poor example (some have (HON)) in the title:
https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202010&subj_in=ENGW&crse_in=1111&schd_in=LEC
