### ISSUE TITLE
There are no results for previous semesters

### ISSUE THREAD

**Issue by dmelcer9** [sandboxnu/searchneu-old#103]
The search only returns results for Spring 2020, all previous semesters are broken.

![image](https://user-images.githubusercontent.com/10052511/70076926-cbce5f00-15cd-11ea-8a31-dcbe0ab8f6b3.png)

**Comment by jasonhemann** [comment]
That is to say, searches in the current semester (i.e. FA2019) and previous semesters return results only for people, and do not return information for courses. As @dmelcer9 notes, SP2020 does work as expected.

**Comment by dajinchu** [comment]
hi all. we are aware of the issue. Northeastern switching to banner v9 wrecked our scraping system pretty bad. working on a fix.

Curious why you two are interested in past semester information?

**Comment by dmelcer9** [comment]
1- see final exam info without logging into myneu
2- which classes have historically been taught which terms by which professors, evening or daytime, etc
3- see course descriptions for classes not being offered next semester (also ties into 2)

**Comment by dajinchu** [comment]
fixed
