### ISSUE TITLE
server.js is 1000 lines

### ISSUE THREAD

**Issue by dajinchu** [sandboxnu/searchneu-old#181]
break server.js up.

current route | what it do | new route
-----------------| -----------------| --------
`GET /search`    | search classes | leave be
`GET /webhook` | facebook webhook verification flow| leave be
`POST /webhook` | facebook webhook | leave be
`POST /addSection` | subscribe to a section | `POST /subscription` w/section hash in body
`POST /removeSection` | unsubscribe to a section | `DELETE /subscription` w/ body
`POST /addClass` | subscribe to a class | `POST /subscription` w/class hash in body
`POST /getUserData` | get info on user subs and name | `POST /user`
`POST /submitFeedback` | send feedback? | `POST /feedback`
`GET /data/*` | json files | remove this endpoint

Steps:

1. Add typescript
2. Pull out logic into files with express routers

**Comment by gamburgm** [comment]
😍
