### ISSUE TITLE
Small phones get screwed

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-old#73]
Small phones are getting kind of screwed. Not sure what's causing the issue and it's hard to reproduce because there aren't that many people with small phones, but definitely an issue. 

![small_iphone](https://user-images.githubusercontent.com/33709622/67908791-37e32080-fb53-11e9-8050-26868ef35b28.png)

**Comment by sarah-witt** [comment]
thanks!

**Comment by ryanhugh** [comment]
Good catch! Here's a easy way to repo in chrome dev tools

![image](https://user-images.githubusercontent.com/5777995/67996828-92e64780-fc27-11e9-94c2-5bb373c04f51.png)

**Comment by gamburgm** [comment]
> Good catch! Here's a easy way to repo in chrome dev tools

TIL you can add iPhone 4 to your list of emulated devices 😄

**Comment by gamburgm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Small Phones get Screwed](https://trello.com/c/wCkSDoze/18-small-phones-get-screwed)

**Comment by amielmon** [comment]
Looking at this really quickly at work and it seems like a quick fix, just have to add a media-query for separate styles on smaller devices
