### ISSUE TITLE
Error with parsing text

### ISSUE THREAD

**Issue by zefwang** [sandboxnu/searchneu-old#77]
I'm not sure where this issue originates, but the em-dash (&#8212;) is replaced with its HTML entity, "& # 8 2 1 2;" (see image for example).
<img width="679" alt="Screen Shot 2019-11-11 at 5 38 59 PM" src="https://user-images.githubusercontent.com/45447059/68626912-6f828e80-04aa-11ea-83b6-ffc9717452e2.png">

**Comment by NEUDitao** [comment]
*its

**Comment by dajinchu** [comment]
the new parsers have this issue. :( gonna look into it asap

**Comment by dajinchu** [comment]
fixed in #68
